const GETREQUEST = "GETREQUEST";
const GETSUCCESS = "GETSUCCESS";
const GETFAILURE = "GETFAILURE";

const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
const GET_PROPERTIES_FAILURE = "GET_PROPERTIES_FAILURE";

const POST_PROPERTY_REQUEST = "POST_PROPERTY_REQUEST";
const POST_PROPERTY_SUCCESS = "POST_PROPERTY_SUCCESS";
const POST_PROPERTY_FAILURE = "POST_PROPERTY_FAILURE";

export { 
    GETREQUEST, GETSUCCESS, GETFAILURE, 
    GET_PROPERTIES_REQUEST, GET_PROPERTIES_SUCCESS, GET_PROPERTIES_FAILURE,
    POST_PROPERTY_REQUEST, POST_PROPERTY_SUCCESS, POST_PROPERTY_FAILURE 
};
